"""
Config module reads config in TOML format and provides settings
"""

import logging
import configparser

config = configparser.ConfigParser()
config.read("file_server.ini")

log_file = config.get("Log", "logfile")
if config.get("Log", "level") == "DEBUG":
    log_level = logging.DEBUG
elif config.get("Log", "level") == "PROD":
    log_level = logging.ERROR

logging.basicConfig(filename=log_file, level=log_level)


def get_working_dir():
    """
    Get working directory from the config
    """
    return config.get("Directories", "working_dir")


def get_filename_length():
    """
    Get the length of autogenerated filename from the config
    """
    return config.getint("Values", "filename_length")


def get_secret_key():
    """
    Get secret key from config
    """
    return config.get("Security", "secret_key").encode("utf-8")
    # return os.environ("SECRET_KEY")

